package org.example;

import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;

@Configuration
@ComponentScan
public class App {
    public static void main(String[] args) {

        ApplicationContext context = new AnnotationConfigApplicationContext(App.class);

        TextEditor textEditor = (TextEditor) context.getBean("textEditor");

        textEditor.input("This picture is what you see when you find yourself walking through BBC Television Centre during the recording of 'Strictly Come Dancing' and you push open a door marked 'Not for broadcast' and walk inside. This picture is what I drew in the team-building workshop when they asked me how I saw the future of our company. This picture is 64 per cent sky, 33 per cent sand and 3 per cent built environment. This picture is what it was like when you told that joke the other night. This picture details the measures that will be taken to ensure a banking crisis on this scale can never happen again. This picture is why I love you. To walk from the front of this picture to the back of this picture would take about 25 minutes. This picture is what I heard when you said you were sorry for any distress caused and that naturally you take full responsibility. This picture is a difficult spot-the-ball competition. This picture is of Simon Cowell's " +
                "life flashing in front of his eyes. Key words in an image library search for this picture might include landscape, barren, sand, empty, sign, cloud, dry, tracks,sky, existential. Key words least likely to result in this picture include Christmas, bouncy, loose, mélange, cosy, beef, nonchalant, cornflakes, splash, companionship. This picture was most likely taken on a Tuesday, possibly a Saturday. This picture reverberates. This picture is concerned more with the spaces between things than it is with the things themselves. This picture is very beautiful. If you took down every billboard advertisement in the world and replaced it with this picture, it would take a while for people to notice. This picture is what I think of your customer service helpline. This picture is worth whatever someone is willing to pay for it. Frequently Asked Questions about this picture include: \"What made you be a picture of that thing?\"; \"Where did you first get the idea to be a picture of that thing?\"; and \"Do you have any plans to be a picture of other things in the future?\" The answers to the Frequently Asked Questions about " +
                "this picture are not as frequent as the questions. I think I once went out with this picture. Someone somewhere thinks I am like this picture, which is a disturbing thought. This picture is what you see when you find yourself walking down a long carpeted corridor in Whitehall towards a door marked 'Big Society' and you push it open and walk inside. This picture would serve a useful function in the Oval Office, or on the walls of the staircase at 10 Downing Street. The place that this picture is a picture of is a real place that exists right now and probably looks very similar to the way it does in this picture. We could both go and stand in this picture if we wanted to. Which is to say, we could both go and stand in the place that this picture is a picture of. If we had been standing there at the time this picture was taken, it would be a different picture. Or possibly just the same picture with us in it. I spy with my little eye " +
                "something in this picture beginning with 's'. This picture is what I'm thinking about whenever you ask me what I'm thinking about. This picture is what my careers development officer saw in me. This picture is a machine for remembering itself. Two X-factor judges were discussing this picture - I forget which ones – and the first one said, \"Wow! This is one of the best pictures I have ever seen!\" and started to cry. The second one said, \"I like this picture but I don't like its choice of material. I would like to see more from this picture in next week's Beatles night!\" This picture is art. This picture doesn't know much about you but it knows what it likes and it doesn't like you. This picture is of a woman in a red dress with a white umbrella running laughing across the sand and into a flock of startled seagulls, but without the startled seagulls, the white umbrella, the red dress and the laughing, running woman. This picture is of the centre ground in American politics. This picture confused me when it came out of the passport photo machine. This picture is of a characterful property in a beach location with plenty of off-street parking. Just beside the person who took this picture is a wooden sign with a camera symbol on it and text reading \"Non-intrusive backdrop to overlaying type.\" This picture is of the losing entry in the RHS Chelsea Flower Show. This picture contains a fencing arrangement which may be marking out a track of some sort. This picture wants to be your friend on Facebook. This picture is what you see when you fall asleep on the Piccadilly Line on the way home and wake up at the last stop and walk up the stairs and outside. This picture could not have been taken any other way.Somewhere to the right of this picture is where I think I dropped my watch. Who knows what's going on either side of this picture. I would guess it's around 11am in this picture. This picture contains a sign that is too far away to read. The small building in this picture is where they keep the on/off switch for the " +
                "Internet. None of us remember where we were when this picture was taken. This picture is your retirement gift after 40 years in service. This picture was taken during a rollover week. Do you have any wallpaper that matches this picture? I would like my hair cut in the style of this picture. The thing beginning with 's' in this picture was 'sand'. This picture was taken a split second after the spaceship disappeared into the clouds. You really have to see this picture.");

        // Lưu ra file PDF
        textEditor.save("output6_4.pdf");
        // Lưu ra file văn bản
        textEditor.save("output6_4.txt");


    }
}
